# Generated by Django 2.1.1 on 2018-09-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=215, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Вид разрешенного использования',
                'verbose_name_plural': 'Виды разрешенного использования',
            },
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='kladr',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='okato',
        ),
        migrations.AddField(
            model_name='parcel',
            name='utilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provernalog.Utilization'),
        ),
    ]
