# Generated by Django 2.1.1 on 2018-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0002_auto_20180907_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilization',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
    ]
