# Generated by Django 2.1.1 on 2018-09-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0003_auto_20180907_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilization',
            name='name',
            field=models.CharField(max_length=345, verbose_name='Назначение'),
        ),
    ]
