# Generated by Django 2.1.1 on 2018-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0004_auto_20180907_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilization',
            name='name',
            field=models.TextField(verbose_name='Назначение'),
        ),
    ]
