# Generated by Django 2.1.1 on 2018-09-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0007_auto_20180914_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='assignation',
            field=models.CharField(blank=True, choices=[('005001001000', 'Нежилое здание'), ('005001002000', 'Жилой дом'), ('005001003000', 'Многоквартирный дом'), ('005001999000', 'Иное'), ('005002001000', 'Жилое'), ('005002001001', 'Комната'), ('005002001002', 'Квартира'), ('005002002000', 'Нежилое'), ('005002999000', 'Иное')], max_length=61, null=True, verbose_name='Назначение'),
        ),
    ]
