# Generated by Django 2.1.1 on 2018-09-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0011_auto_20180925_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAppraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('name', models.CharField(max_length=240)),
                ('region', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubgroupAppraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_id', models.IntegerField()),
                ('name', models.CharField(max_length=240)),
                ('region', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provernalog.GroupAppraise')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='group_appraise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provernalog.GroupAppraise'),
        ),
    ]
