# Generated by Django 2.1.1 on 2018-09-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0013_auto_20180928_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroupappraise',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provernalog.GroupAppraise'),
        ),
    ]
