# Generated by Django 2.1.1 on 2018-10-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0014_subgroupappraise_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroupappraise',
            name='region',
        ),
        migrations.RemoveField(
            model_name='subgroupappraise',
            name='type',
        ),
    ]
