# Generated by Django 2.1.2 on 2018-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0015_auto_20181002_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelAggregate',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика Объектов',
                'verbose_name_plural': 'Статистика Объектов',
                'proxy': True,
                'indexes': [],
            },
            bases=('provernalog.parcel',),
        ),
        migrations.AddField(
            model_name='parcel',
            name='date_relevance',
            field=models.DateField(blank=True, null=True, verbose_name='Дата актуальности'),
        ),
    ]
