# Generated by Django 2.1.2 on 2018-10-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0016_auto_20181010_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('region', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('source_url', models.URLField(blank=True, max_length=360, null=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
            },
        ),
    ]
