# Generated by Django 2.1.2 on 2019-02-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0018_auto_20181012_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelStatic',
            fields=[
            ],
            options={
                'verbose_name': 'Общая статистика',
                'verbose_name_plural': 'Общая статистика',
                'proxy': True,
                'indexes': [],
            },
            bases=('provernalog.parcel',),
        ),
        migrations.AlterModelOptions(
            name='parcelaggregate',
            options={'verbose_name': 'Статистика Объекта', 'verbose_name_plural': 'Статистика Объектов'},
        ),
    ]
