# Generated by Django 2.1.2 on 2019-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0019_auto_20190208_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='evaluativefactor',
            name='parcel',
            field=models.ManyToManyField(blank=True, through='provernalog.ValueFactor', to='provernalog.Parcel'),
        ),
    ]
