# Generated by Django 2.1.2 on 2019-02-14 08:42

from django.db import migrations, models
import provernalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0021_auto_20190212_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='hash',
            field=models.CharField(blank=True, default=provernalog.models.support_hash, max_length=96, null=True, verbose_name='Hash'),
        ),
    ]
