# Generated by Django 2.1.2 on 2019-02-14 19:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provernalog', '0022_support_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=240, verbose_name='Данные покупателя')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='Инн')),
                ('user_id', models.CharField(default=shop.models.get_default_as_uuid, max_length=62, verbose_name='Уникальный номер пользователя')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=120, verbose_name='Email покупателя')),
                ('status', models.CharField(blank=True, choices=[('processed', 'В процессе'), ('success', 'Успешно'), ('fail', 'Не оплачено')], max_length=45, null=True)),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('payment_id', models.CharField(blank=True, max_length=62, null=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма заказа')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=780, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название для чека')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Картинка товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('payment_subject', models.CharField(blank=True, choices=[('commodity', 'Товар'), ('excise', 'Подакцизный товар'), ('job', 'Работа'), ('service', 'Услуга'), ('intellectual_activity', 'Результаты интеллектуальной деятельности'), ('payment', 'Платеж'), ('agent_commission', 'Агентское вознаграждение'), ('composite', 'Несколько вариантов'), ('another', 'Другое')], max_length=120, null=True, verbose_name='Признак предмета расчета')),
                ('payment_mode', models.CharField(blank=True, choices=[('full_prepayment', 'Полная предоплата'), ('partial_prepayment', 'Частичная предоплата'), ('advance', 'Аванс'), ('full_payment', 'Полный расчет')], max_length=120, null=True, verbose_name='Признак способа расчета')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='order',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provernalog.Parcel'),
        ),
    ]
