# Generated by Django 2.1.2 on 2018-10-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provernalog', '0018_auto_20181012_0910'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=360)),
                ('date_relevance', models.DateField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provernalog.City')),
            ],
            options={
                'verbose_name': 'Перечень',
                'verbose_name_plural': 'Перечни',
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date_added',), 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='date_added',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(verbose_name='Текст отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=360, verbose_name='Заголовок'),
        ),
    ]
