# Generated by Django 2.1.2 on 2019-03-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20181017_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcereport',
            options={'ordering': ('region__region',), 'verbose_name': 'Перечень', 'verbose_name_plural': 'Перечень'},
        ),
    ]
