# Generated by Django 2.1.2 on 2019-03-15 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('async_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsertask',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='parsed_parcels',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество загруженных объектов'),
        ),
    ]
